width=280
height=150
location=center
allow_images=false
image_size=0
insensitive=true
matching=multi-contains
hide_scroll=true
key_up=Up,k
key_down=Down,j
key_left=Left,h
key_right=Right,l
hide_search=true
