width=900
height=600
location=center
show=dmenu
allow_images=true
image_size=280
parse_search=true
insensitive=true
hide_scroll=false
hide_search=true
halign=fill
content_halign=center
key_up=Up,k
key_down=Down,j
key_left=Left,h
key_right=Right,l
